#!/bin/sh
LANG="fr_FR.UTF-8"; export LANG
SHELL="/bin/bash"; export SHELL
SHLVL="2"; export SHLVL
PWD="/home/docker"; export PWD
SSH_CLIENT="172.17.42.1\ 50126\ 22"; export SSH_CLIENT
LOGNAME="docker"; export LOGNAME
USER="docker"; export USER
MAIL="/var/mail/docker"; export MAIL
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games":"$PATH"; export PATH
SSH_CONNECTION="172.17.42.1\ 50126\ 172.17.42.134\ 22"; export SSH_CONNECTION
HOME="/home/docker"; export HOME
_="/usr/bin/xpra"; export _
cd "/home/docker"
_XPRA_PYTHON="/usr/bin/python"
_XPRA_SCRIPT="/usr/bin/xpra"

if which "$_XPRA_PYTHON" > /dev/null && [ -e "$_XPRA_SCRIPT" ]; then
    # Happypath:
    exec "$_XPRA_PYTHON" "$_XPRA_SCRIPT" "$@"
else
    cat >&2 <<END
    Could not find one or both of '$_XPRA_PYTHON' and '$_XPRA_SCRIPT'
    Perhaps your environment has changed since the xpra server was started?
    I'll just try executing 'xpra' with current PATH, and hope...
END
    exec xpra "$@"
fi
